{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}-bigwave-dags-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote}}
{{- end }}
---
{{- if .Values.logsPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}-bigwave-logs-pvc
spec:
  accessModes:
    - {{ .Values.logsPersistence.accessMode }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.logsPersistence.size | quote}}
{{- end }}