apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow-nfs.fullname" . }}-logs-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-logs-server
  template:
    metadata:
      labels:
        role: nfs-logs-server
    spec:
      containers:
        - name: nfs-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /logs
              name: {{ template "airflow-nfs.fullname" . }}-logs-nfs-pvc
      volumes:
        - name: {{ template "airflow-nfs.fullname" . }}-logs-nfs-pvc
          persistentVolumeClaim:
            claimName: {{ template "airflow-nfs.fullname" . }}-logs-nfs-pvc