apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow-nfs.fullname" . }}-logs-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-logs-server